blueprint:
  name: Confirmable Reminder with Timer Reset
  description: >
    Sends a reminder if a task (like cleaning) hasn't been done in a while.
    Offers a Yes/No confirmation. 'Yes' resets a timer. Supports mobile device or group notifications.
  domain: automation
  input:
    task_name:
      name: Task Name
      description: A friendly name for the task (e.g., "Clean Toilet").
      selector:
        text:
    date_entity:
      name: Date/Time Entity
      description: An input_datetime entity that stores the last time the task was completed.
      selector:
        entity:
          domain: input_datetime
    reminder_interval:
      name: Reminder Interval (Days)
      description: How many days before sending a reminder?
      default: 7
      selector:
        number:
          min: 1
          max: 60
          unit_of_measurement: days
    notification_target:
      name: Notification Target (Device or Group)
      description: >
        The notify service to use (e.g., notify.mobile_app_your_phone or notify.all_users).
        Must be a valid notify.* service from your setup.
      selector:
        text:
    reminder_toggle:
      name: Reminder Toggle (Optional)
      description: Optional input_boolean to enable or disable reminders.
      default: ""
      selector:
        entity:
          domain: input_boolean

trigger:
  - platform: time
    at: "09:00:00"

condition:
  - condition: template
    value_template: >
      {% set last_done = states[input.date_entity] %}
      {% if not last_done %}
        false
      {% else %}
        {% set last = as_datetime(last_done) %}
        {% set days_passed = (now() - last).days %}
        {{ days_passed >= input.reminder_interval }}
      {% endif %}

  - condition: or
    conditions:
      - condition: template
        value_template: "{{ input.reminder_toggle == '' }}"
      - condition: state
        entity_id: !input reminder_toggle
        state: "on"

action:
  - service: !input notification_target
    data:
      message: "Have you {{ input.task_name.lower() }} recently?"
      title: "Reminder: {{ input.task_name }}"
      data:
        actions:
          - action: "YES_{{ input.task_name | slugify }}"
            title: "Yes"
          - action: "NO_{{ input.task_name | slugify }}"
            title: "No"

mode: single
